{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-custom-exchanger-0.0.9.jar",
          "url": "config-custom-exchanger-0.0.9.jar",
          "size": 7384,
          "sha512": "2fa9705cd706e379518ece5cd5f594382682d2f418f5760097f2d95a1e081b79f3c3afec8b0cd62426753f30f3e592b2b309814950a7847fffb10d7190a5ba42",
          "sha256": "099f0acc1b67ffb4e393c573772c00466941230567105868250ee330440ef626",
          "sha1": "22ede80667603e4cf49d03bf23209e602c48fea8",
          "md5": "638d9def0743a262d2bbdb487e5e7dd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "ssm",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "sts",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.9.jar",
          "url": "config-custom-exchanger-0.0.9.jar",
          "size": 7384,
          "sha512": "2fa9705cd706e379518ece5cd5f594382682d2f418f5760097f2d95a1e081b79f3c3afec8b0cd62426753f30f3e592b2b309814950a7847fffb10d7190a5ba42",
          "sha256": "099f0acc1b67ffb4e393c573772c00466941230567105868250ee330440ef626",
          "sha1": "22ede80667603e4cf49d03bf23209e602c48fea8",
          "md5": "638d9def0743a262d2bbdb487e5e7dd6"
        }
      ]
    }
  ]
}
