{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-custom-exchanger-0.0.2.jar",
          "url": "config-custom-exchanger-0.0.2.jar",
          "size": 8182,
          "sha512": "1071d70286e4f31d14489b799978ad4c879c0394082ebc38d6645965b01aa4ee0d3e70da4cb35a1b1485d5b1e00245d37582fcf7167c2c730f5eb57d3d3b6aeb",
          "sha256": "a3717e88ddf097a3a4ed085a7570ad19f9b2d2dadd7d306f278e732810d0b35a",
          "sha1": "f8be26ef6cc7ae49c5e5aacaa9201675471caab4",
          "md5": "1bc78d636e51794ac14b02b43ac082e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-ssm",
          "version": {
            "requires": "1.12.230"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.2.jar",
          "url": "config-custom-exchanger-0.0.2.jar",
          "size": 8182,
          "sha512": "1071d70286e4f31d14489b799978ad4c879c0394082ebc38d6645965b01aa4ee0d3e70da4cb35a1b1485d5b1e00245d37582fcf7167c2c730f5eb57d3d3b6aeb",
          "sha256": "a3717e88ddf097a3a4ed085a7570ad19f9b2d2dadd7d306f278e732810d0b35a",
          "sha1": "f8be26ef6cc7ae49c5e5aacaa9201675471caab4",
          "md5": "1bc78d636e51794ac14b02b43ac082e0"
        }
      ]
    }
  ]
}
