{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-custom-exchanger-0.0.2.jar",
          "url": "config-custom-exchanger-0.0.2.jar",
          "size": 8168,
          "sha512": "2b5aeee21994948c7c435a4f3bcac255adb8a48fda7a7204920e87a0f573a2d5cf2d342c1900646854e4d1954f0bdead9488de144cc544eb4ed4849babe1acbe",
          "sha256": "1c6926e28bcfca0802e938a37d8940a647219b9ae835affe9b799d5fa2ad63d5",
          "sha1": "758874f06664fd7cdefb84ed199cb682ad22833d",
          "md5": "dac2ef9f396b609abd82a643a1ee2990"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-ssm",
          "version": {
            "requires": "1.12.230"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.2.jar",
          "url": "config-custom-exchanger-0.0.2.jar",
          "size": 8168,
          "sha512": "2b5aeee21994948c7c435a4f3bcac255adb8a48fda7a7204920e87a0f573a2d5cf2d342c1900646854e4d1954f0bdead9488de144cc544eb4ed4849babe1acbe",
          "sha256": "1c6926e28bcfca0802e938a37d8940a647219b9ae835affe9b799d5fa2ad63d5",
          "sha1": "758874f06664fd7cdefb84ed199cb682ad22833d",
          "md5": "dac2ef9f396b609abd82a643a1ee2990"
        }
      ]
    }
  ]
}
