{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-custom-exchanger-0.0.3.jar",
          "url": "config-custom-exchanger-0.0.3.jar",
          "size": 8153,
          "sha512": "a5776cc1efde7f967920afa75f4df61e0ead509282e99ea8ed27c614d264553e0bb2e55644a49a48ce0af5f438e6524bd7f1bb757ae086d24443c48473679152",
          "sha256": "7bc7aef0975b304e2fe4ae014b288a7945d8e6b9414c53e3e32349b490d48bff",
          "sha1": "416bbde025cf3abf402f13d250ae3f5aaf6e83da",
          "md5": "18ba93b8b61b2e539f15c2f1857b89c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "ssm",
          "version": {
            "requires": "2.17.209"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.3.jar",
          "url": "config-custom-exchanger-0.0.3.jar",
          "size": 8153,
          "sha512": "a5776cc1efde7f967920afa75f4df61e0ead509282e99ea8ed27c614d264553e0bb2e55644a49a48ce0af5f438e6524bd7f1bb757ae086d24443c48473679152",
          "sha256": "7bc7aef0975b304e2fe4ae014b288a7945d8e6b9414c53e3e32349b490d48bff",
          "sha1": "416bbde025cf3abf402f13d250ae3f5aaf6e83da",
          "md5": "18ba93b8b61b2e539f15c2f1857b89c9"
        }
      ]
    }
  ]
}
