{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "software.amazon.awssdk",
          "module": "ssm",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.3.jar",
          "url": "config-custom-exchanger-0.0.3.jar",
          "size": 8153,
          "sha512": "f87391e6eb30f6bb788342d4dcbfe773cf286aa5fb60a16f523da18d7d3a3e37a977e80b4d35bceeeef3a2b23baaba76eefdcaf665c75ea08f0f6e0a01020622",
          "sha256": "0ec6b37233de7900e04fd5d85d5ca08a091fd9158b4a862ada9d210b55b0ddfc",
          "sha1": "0bdb5c55ffee55be2208ea354ae8be912611324d",
          "md5": "1369f7fe65289a64d4d3a61a3a2ce45c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "ssm",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.3.jar",
          "url": "config-custom-exchanger-0.0.3.jar",
          "size": 8153,
          "sha512": "f87391e6eb30f6bb788342d4dcbfe773cf286aa5fb60a16f523da18d7d3a3e37a977e80b4d35bceeeef3a2b23baaba76eefdcaf665c75ea08f0f6e0a01020622",
          "sha256": "0ec6b37233de7900e04fd5d85d5ca08a091fd9158b4a862ada9d210b55b0ddfc",
          "sha1": "0bdb5c55ffee55be2208ea354ae8be912611324d",
          "md5": "1369f7fe65289a64d4d3a61a3a2ce45c"
        }
      ]
    }
  ]
}
