{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-custom-exchanger-0.0.8.jar",
          "url": "config-custom-exchanger-0.0.8.jar",
          "size": 7470,
          "sha512": "471b23adbf9dc8869495281cf38883d94e18a03e979bfd110104b2f5d0ac7981762148d9572d5b68fabdd1aa63a6fa5f555112ab4f969871644ea1c3a8624c2c",
          "sha256": "2482f8c4beca724c1875f103e0e8e05372a4abab3480aeb561a13d7f41c1799b",
          "sha1": "9afe8f21b4c2529d8cc062d4b936a11c7de49803",
          "md5": "3621c7c63f918335ac5cec18cca47bfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "ssm",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "sts",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.8.jar",
          "url": "config-custom-exchanger-0.0.8.jar",
          "size": 7470,
          "sha512": "471b23adbf9dc8869495281cf38883d94e18a03e979bfd110104b2f5d0ac7981762148d9572d5b68fabdd1aa63a6fa5f555112ab4f969871644ea1c3a8624c2c",
          "sha256": "2482f8c4beca724c1875f103e0e8e05372a4abab3480aeb561a13d7f41c1799b",
          "sha1": "9afe8f21b4c2529d8cc062d4b936a11c7de49803",
          "md5": "3621c7c63f918335ac5cec18cca47bfc"
        }
      ]
    }
  ]
}
