{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-custom-exchanger-0.0.4.jar",
          "url": "config-custom-exchanger-0.0.4.jar",
          "size": 8153,
          "sha512": "2d96d5ec077096490270dca86434864fce9e6274ea3302e997fca05759578d80ef5cc7f15ab71557b48045e1d0d415603ecc2e65ade62615ea6473c5ffce4d0c",
          "sha256": "cd571f7e2b2187dc744219c339bf9ac3953b3bedbdd4c334a154aa3cb0a1bd34",
          "sha1": "affc2fe31c40b59d88d66eb3e51c3df108b78f36",
          "md5": "1c57243fb2b0b2b69d899e5ca9716a09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "ssm",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.4.jar",
          "url": "config-custom-exchanger-0.0.4.jar",
          "size": 8153,
          "sha512": "2d96d5ec077096490270dca86434864fce9e6274ea3302e997fca05759578d80ef5cc7f15ab71557b48045e1d0d415603ecc2e65ade62615ea6473c5ffce4d0c",
          "sha256": "cd571f7e2b2187dc744219c339bf9ac3953b3bedbdd4c334a154aa3cb0a1bd34",
          "sha1": "affc2fe31c40b59d88d66eb3e51c3df108b78f36",
          "md5": "1c57243fb2b0b2b69d899e5ca9716a09"
        }
      ]
    }
  ]
}
