{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-custom-exchanger-0.0.5.jar",
          "url": "config-custom-exchanger-0.0.5.jar",
          "size": 6904,
          "sha512": "9e21a80dc5531d6550aee5ded8195e793b37ceb8c931474ec3994595bc8701e8668b8b724eece5ad108b405e145f6dc224c555af0a4f96d5c9a141132d412d1e",
          "sha256": "5ee63c3909cb5807fdea93b65bc939a64a739c56ebca9b7367283bec53e9affe",
          "sha1": "53e6ea726ea5062add0ba5196d1669c22116df0d",
          "md5": "319e99d77a2f2869cb3cefde05bf0ec1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "ssm",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.5.jar",
          "url": "config-custom-exchanger-0.0.5.jar",
          "size": 6904,
          "sha512": "9e21a80dc5531d6550aee5ded8195e793b37ceb8c931474ec3994595bc8701e8668b8b724eece5ad108b405e145f6dc224c555af0a4f96d5c9a141132d412d1e",
          "sha256": "5ee63c3909cb5807fdea93b65bc939a64a739c56ebca9b7367283bec53e9affe",
          "sha1": "53e6ea726ea5062add0ba5196d1669c22116df0d",
          "md5": "319e99d77a2f2869cb3cefde05bf0ec1"
        }
      ]
    }
  ]
}
