{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-custom-exchanger-0.0.5.jar",
          "url": "config-custom-exchanger-0.0.5.jar",
          "size": 6904,
          "sha512": "7d95aea1093f2c959807ae469a7e0477ee5abb9612c94a8fbca7f50e7fa3af28f77df87964d076cabaea030fed46606615d82fe6b65cb1168f01d6386ae28355",
          "sha256": "d4b4da1fa2cf86756c8e263b5be690d501ebce773f45ba2adbc214f8f01dc066",
          "sha1": "8954f82e6d0d11f5762a23ca8ef9f017e8b693e5",
          "md5": "11a06cad5b3201c708f1a5bf4136a0e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "ssm",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.5.jar",
          "url": "config-custom-exchanger-0.0.5.jar",
          "size": 6904,
          "sha512": "7d95aea1093f2c959807ae469a7e0477ee5abb9612c94a8fbca7f50e7fa3af28f77df87964d076cabaea030fed46606615d82fe6b65cb1168f01d6386ae28355",
          "sha256": "d4b4da1fa2cf86756c8e263b5be690d501ebce773f45ba2adbc214f8f01dc066",
          "sha1": "8954f82e6d0d11f5762a23ca8ef9f017e8b693e5",
          "md5": "11a06cad5b3201c708f1a5bf4136a0e4"
        }
      ]
    }
  ]
}
