{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-custom-exchanger-0.0.6.jar",
          "url": "config-custom-exchanger-0.0.6.jar",
          "size": 7047,
          "sha512": "05167952ca3203ab9e38e24fe98ceea272946a98f4808c3e7efffcb6b00504b736d582b91b2166b3276fdeae09438727e7b89db3b0bbb6f3b63ceefc9b3a0668",
          "sha256": "6d01c526752268378982d10b3a476eae0fa75e2413bc13f67d394628c949dbbc",
          "sha1": "95b3e870f1398f521124e48338e0d409d08f0d06",
          "md5": "149c386140d9f8241c26de028398af64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "ssm",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.6.jar",
          "url": "config-custom-exchanger-0.0.6.jar",
          "size": 7047,
          "sha512": "05167952ca3203ab9e38e24fe98ceea272946a98f4808c3e7efffcb6b00504b736d582b91b2166b3276fdeae09438727e7b89db3b0bbb6f3b63ceefc9b3a0668",
          "sha256": "6d01c526752268378982d10b3a476eae0fa75e2413bc13f67d394628c949dbbc",
          "sha1": "95b3e870f1398f521124e48338e0d409d08f0d06",
          "md5": "149c386140d9f8241c26de028398af64"
        }
      ]
    }
  ]
}
