{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-custom-exchanger-0.0.6.jar",
          "url": "config-custom-exchanger-0.0.6.jar",
          "size": 7047,
          "sha512": "74dd415fb90ad261b02f84b1d8db6790cd25a78b392907304ebd8c05d27521e969f89f3f62c666231c3e2ee1426ad15bd1fb6b466faad47915674c376dbcf79c",
          "sha256": "212e7c2b091c12e294a36f9e77ed50a9ed89e45c946f2e7765fe623d48c6d487",
          "sha1": "45dec42571d4595b3d7640301a386de2956e7006",
          "md5": "c64afa07c8e707d9719d1e0841b93baf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.3.12.RELEASE"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "ssm",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.6.jar",
          "url": "config-custom-exchanger-0.0.6.jar",
          "size": 7047,
          "sha512": "74dd415fb90ad261b02f84b1d8db6790cd25a78b392907304ebd8c05d27521e969f89f3f62c666231c3e2ee1426ad15bd1fb6b466faad47915674c376dbcf79c",
          "sha256": "212e7c2b091c12e294a36f9e77ed50a9ed89e45c946f2e7765fe623d48c6d487",
          "sha1": "45dec42571d4595b3d7640301a386de2956e7006",
          "md5": "c64afa07c8e707d9719d1e0841b93baf"
        }
      ]
    }
  ]
}
