{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-gateway",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.1.jar",
          "url": "config-custom-exchanger-0.0.1.jar",
          "size": 6982,
          "sha512": "6bc9d638b7ff345db7d5d520d296a3dddd27759ce4175f3679e597152ff4b3d31d849fae815591683040bb67e88a39b20cfa68267ebb7d86d464c306c37feb92",
          "sha256": "3eb18259dcbfb5fa51f36215a886ed158f75ef6c7e2500887e2bb3ec5e053e21",
          "sha1": "2d8e99e2d3438f4bc7be5a227808fbd137039478",
          "md5": "1646f8fcad0e99216eeaa17407002b05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-ssm",
          "version": {
            "requires": "1.12.230"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-gateway",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.1.jar",
          "url": "config-custom-exchanger-0.0.1.jar",
          "size": 6982,
          "sha512": "6bc9d638b7ff345db7d5d520d296a3dddd27759ce4175f3679e597152ff4b3d31d849fae815591683040bb67e88a39b20cfa68267ebb7d86d464c306c37feb92",
          "sha256": "3eb18259dcbfb5fa51f36215a886ed158f75ef6c7e2500887e2bb3ec5e053e21",
          "sha1": "2d8e99e2d3438f4bc7be5a227808fbd137039478",
          "md5": "1646f8fcad0e99216eeaa17407002b05"
        }
      ]
    }
  ]
}
