{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lguplus.iptv",
    "module": "config-custom-exchanger",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-gateway",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.1.jar",
          "url": "config-custom-exchanger-0.0.1.jar",
          "size": 6982,
          "sha512": "2a7530752efdb5248235e005c0b5ac45f8d1a4e5a28a76a301f24b555bfe4161768bbef9ca1541f9cc89e8dc1a24e4126d7363b885537e9a4688771a650df7c1",
          "sha256": "a3faf4dc3c0cec37349386a13dab0a75134ce36c086d951162ead9169e8cb0fe",
          "sha1": "d03b561cd8a7744eb03a4b7dae3053773a822a7f",
          "md5": "b99604e021bc8ee9ebbbef0a5941eae2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-ssm",
          "version": {
            "requires": "1.12.230"
          }
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-gateway",
          "version": {
            "requires": "3.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "config-custom-exchanger-0.0.1.jar",
          "url": "config-custom-exchanger-0.0.1.jar",
          "size": 6982,
          "sha512": "2a7530752efdb5248235e005c0b5ac45f8d1a4e5a28a76a301f24b555bfe4161768bbef9ca1541f9cc89e8dc1a24e4126d7363b885537e9a4688771a650df7c1",
          "sha256": "a3faf4dc3c0cec37349386a13dab0a75134ce36c086d951162ead9169e8cb0fe",
          "sha1": "d03b561cd8a7744eb03a4b7dae3053773a822a7f",
          "md5": "b99604e021bc8ee9ebbbef0a5941eae2"
        }
      ]
    }
  ]
}
